# Generated by Django 5.1 on 2024-09-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_alter_students_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(max_length=5),
        ),
    ]
